version: '2'

services:
    tensorflow:
        build: .
        container_name: 'tensorflow-examples'
        env_file: .env
        volumes:
            - ./models:/tensorflow/models
        command: bash -c "python3 object_detection/generate_tfrecord.py --csv_input=object_detection/images/train_labels.csv --image_dir=object_detection/images/train --output_path=object_detection/images/train.record && python3 object_detection/generate_tfrecord.py --csv_input=object_detection/images/test_labels.csv --image_dir=object_detection/images/test --output_path=object_detection/images/test.record && python3 object_detection/train.py --train_dir=object_detection/training/ --pipeline_config_path=object_detection/training/ssd_mobilenet_v2_quantized_300x300_coco.config && python3 export_tflite_ssd_graph.py --pipeline_config_path=/tensorflow/object-detection/models/research/object_detection/training/ssd_mobilenet_v2_quantized_300x300_coco.config --trained_checkpoint_prefix=/tensorflow/object-detection/models/research/object_detection/training/model.ckpt-200 --output_directory=/tensorflow/object-detection/tflite-model --add_postprocessing_op=true"
        ports:
            - 8888:8888
