version: '2'

services:
  tensorflow:
    build: .
    container_name: 'tensorflow-examples'
    env_file: .env
    volumes:
      - ./models:/tensorflow/models
      - ./tflite-model:/tensorflow/tflite-model
    command: bash -c "python3 object_detection/xml_to_csv.py && python3 object_detection/generate_tfrecord.py --csv_input=object_detection/images/train_labels.csv --image_dir=object_detection/images/train --output_path=object_detection/images/train.record && python3 object_detection/generate_tfrecord.py --csv_input=object_detection/images/test_labels.csv --image_dir=object_detection/images/test --output_path=object_detection/images/test.record && python3 object_detection/train.py --train_dir=object_detection/training/ --pipeline_config_path=object_detection/training/ssd_mobilenet_v2_quantized_300x300_coco.config && python3 object_detection/export_tflite_ssd_graph.py --pipeline_config_path=object_detection/training/ssd_mobilenet_v2_quantized_300x300_coco.config --trained_checkpoint_prefix=object_detection/training/model.ckpt-107 --output_directory=/tensorflow/tflite-model --add_postprocessing_op=true"
    ports:
      - 8888:8888
