item {
  id: 101
  name: 'object'
}

item {
  id: 1
  name: 'circle 1'
}

item {
  id: 2
  name: 'circle 2'
}

item {
  id: 3
  name: 'circle 3'
}

item {
  id: 4
  name: 'circle 4'
}

item {
  id: 5
  name: 'circle 5'
}

item {
  id: 6
  name: 'circle 6'
}
